# config.yaml
name: 3D Blueprint Generator
version: "3.31"
slug: blueprint_generator
description: "Generate 3D home blueprints from Bluetooth sensor data"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto

# Default values
options:
  log_level: info
  processing_interval: 300
  enable_ai_refinement: true
  use_room_areas: true
  ha_token: ""
  static_device_detection_enabled: true
  movement_threshold_meters: 0.5
  static_device_min_observations: 5
  time_window_seconds: 300
  static_anchor_confidence_decay_hours: 1.0
  max_dynamic_anchors: 10

# Schema for configuration UI
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  processing_interval: int(60,3600)
  enable_ai_refinement: bool
  use_room_areas: bool
  ha_token: password
  static_device_detection_enabled: bool
  movement_threshold_meters: float(0.1,5.0)
  static_device_min_observations: int(3,20)
  time_window_seconds: int(60,3600)
  static_anchor_confidence_decay_hours: float(0.1,24.0)
  max_dynamic_anchors: int(1,20)

# Container configuration
map:
  - data:rw
# Expose the API port
ports:
  '8000/tcp': 8000
ports_description:
  '8000/tcp': 'Web interface'

# Home Assistant API access - comprehensive permissions
auth_api: true
homeassistant_api: true
hassio_api: true
hassio_role: default
supervisor_api: true

# UI Configuration
ingress: true
ingress_port: 8000
panel_icon: mdi:floor-plan
panel_title: "3D Blueprint Generator"
webui: "http://[HOST]:[PORT:8000]/"
