# config.yaml
name: 3D Blueprint Generator
version: "1.95"
slug: blueprint_generator
description: "Generate 3D home blueprints from Bluetooth sensor data"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto

# Default values
options:
  log_level: info
  processing_interval: 300
  enable_ai_refinement: true
  use_room_areas: true

# Schema for configuration UI
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  processing_interval: int(60,3600)
  enable_ai_refinement: bool
  use_room_areas: bool

# Container configuration
map:
  - data:rw
# Expose the API port
ports:
  '8001/tcp': 8001
ports_description:
  '8001/tcp': 'Web interface/API port'

# UI Configuration
ingress: true
ingress_port: 8000
panel_icon: mdi:floor-plan
panel_title: "3D Blueprint Generator"
webui: "http://[HOST]:[PORT:8001]/"
