# config.yaml
name: 3D Blueprint Generator
version: "1.78" # Or your actual version
slug: blueprint_generator # Choose a unique slug
description: Generates 3D blueprints using BLE sensors and HA data
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto

# Default values
options: # Default values (usually read from your config.json or set here)
  log_level: info
  # Database options can have defaults or be empty if user MUST provide them
  db_host: "core-mariadb"
  db_port: 3306
  db_database: "homeassistant"
  db_user: ""
  db_password: ""
  # Leave fixed_sensors empty here, user provides values
  fixed_sensors: {}

# Schema for configuration UI
schema: # Define structure and types for the UI Configuration tab
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  db_host: str
  db_port: port
  db_database: str
  db_user: str
  db_password: password # Use 'password' type for masking in UI
  fixed_sensors: "dict(str, dict(x=float, y=float, z=float))"

# Container and network configuration
# Map the /data directory inside the container (required for options.json)
# Map others if needed (like /config or /share)
map:
  - data:rw
# Expose the API port
ports:
  '5000/tcp': 5000
ports_description:
  '5000/tcp': 'Web interface/API port'

# UI Configuration
ingress: true
ingress_port: 5000
panel_icon: mdi:floor-plan
