build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.9-alpine3.16
  amd64: ghcr.io/home-assistant/amd64-base-python:3.9-alpine3.16
  armhf: ghcr.io/home-assistant/armhf-base-python:3.9-alpine3.16
  armv7: ghcr.io/home-assistant/armv7-base-python:3.9-alpine3.16
  i386: ghcr.io/home-assistant/i386-base-python:3.9-alpine3.16

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: 3D Blueprint Generator"
  org.opencontainers.image.description: "Generate 3D home blueprints from Bluetooth sensor data"
  org.opencontainers.image.source: "https://github.com/delicioushouse/home-assistant_3d_blueprint_generator"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.version: "1.06"
  org.opencontainers.image.authors: "brendan3394@gmail.com"
