build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.9-alpine3.16
  amd64: ghcr.io/home-assistant/amd64-base-python:3.9-alpine3.16
  armhf: ghcr.io/home-assistant/armhf-base-python:3.9-alpine3.16
  armv7: ghcr.io/home-assistant/armv7-base-python:3.9-alpine3.16
  i386: ghcr.io/home-assistant/i386-base-python:3.9-alpine3.16

codenotary:
  base_image: notary@home-assistant.io
  signer: brendan3394@gmail.com

args:
  TEMPIO_VERSION: "2021.09.0"
  BUILD_ARCH: ""
  BUILD_DATE: ""
  BUILD_DESCRIPTION: "Generate 3D home blueprints from Bluetooth sensor data"
  BUILD_NAME: "3D Blueprint Generator"
  BUILD_REF: ""
  BUILD_REPOSITORY: ""
  BUILD_VERSION: ""

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: 3D Blueprint Generator"
  org.opencontainers.image.description: "Generate 3D home blueprints from Bluetooth sensor data"
  org.opencontainers.image.source: "https://github.com/DeliciousHouse/Home-Assistant_3D_Blueprint_Generator"
  org.opencontainers.image.licenses: "MIT"
