name: "3D Blueprint Generator"
version: "1.36"
slug: "blueprint_generator"
description: "Generate 3D home blueprints from Bluetooth sensor data"
url: "https://github.com/delicioushouse/home-assistant_3d_blueprint_generator"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false

# Add-on options
options:
  database_host: "core-mariadb"
  database_port: 3306
  database_name: "homeassistant"
  database_username: "homeassistant"
  database_password: ""
  min_rssi: -75
  update_interval: 5

# Schema for options validation
schema:
  database_host: str
  database_port: port
  database_name: str
  database_username: str
  database_password: password
  min_rssi: int
  update_interval: int

# Add-on ports
ports:
  8000/tcp: null

# Add-on ports description
ports_description:
  8000/tcp: Web interface

# Host requirements
host_network: false
hassio_api: true
auth_api: true

# Auto-update
uart: true

# Required dependencies
map:
  - share:rw
  - config:ro

# Dependencies
services:
  - mysql:want

# Ingress configuration
ingress: true
ingress_port: 8000
panel_icon: mdi:floor-plan
panel_title: 3D Blueprint
panel_admin: true

# Watchdog
watchdog: http://[HOST]:8000/api/health

# Replace with just the permissions you need
protection: "supervisor"  # Only talk to Supervisor API
devices: []  # No device access needed
homeassistant_api: true  # Read Home Assistant entities

# Update database access
services:
  - mysql:need

# Docker configuration
image: "ghcr.io/delicioushouse/blueprint-generator-{arch}"
