name: Builder

env:
  BUILD_ARGS: "--test"
  MONITORED_FILES: "build.yaml config.yaml Dockerfile rootfs"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Add-on
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from config.yaml
        id: config_version
        run: |
          VERSION=$(grep 'version:' config.yaml | sed 's/.*"\([0-9.]*\)".*/\1/')
          echo "config_version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

      - name: Get version and lowercase owner
        id: prep
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Use version from config.yaml for main branch
            version="${{ steps.config_version.outputs.config_version }}"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # Use tag version if this is a tag
            version="${{ github.ref_name }}"
            version=${version#v}  # Remove 'v' prefix if present
          else
            # For PRs and other branches
            version="dev"
          fi

          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "Building version: ${version}"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .  # Use root context now (no subdirectory)
          file: ./Dockerfile  # Dockerfile is in the root now
          platforms: linux/${{ matrix.arch }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ steps.prep.outputs.owner }}/blueprint-generator-${{ matrix.arch }}:${{ steps.prep.outputs.version }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base-python:3.9-alpine3.16
            BUILD_VERSION=${{ steps.prep.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update repository.json version
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION="${{ steps.prep.outputs.version }}"
          if [ -f "repository.json" ]; then
            sed -i "s/\"version\": \"[0-9.]*\"/\"version\": \"${VERSION}\"/" repository.json
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add repository.json
            git commit -m "Update version to ${VERSION} in repository.json" || echo "No changes to commit"
            git push || echo "No changes to push"
          else
            echo "Warning: repository.json not found"
          fi